#!/bin/csh -f


rm -rf ./live.txt

#wget https://raw.githubusercontent.com/wolfcode9/OpenChannel/main/live.txt
## Normal
wget https://raw.githubusercontent.com/wolfcode9/d25d221074c7b34d/main/d3ef48d76c053b24/6df8af2d858ae0c4
## 18
wget https://raw.githubusercontent.com/wolfcode9/d25d221074c7b34d/main/d3ef48d76c053b24/d919fe9602ad13f7

mv ./6df8af2d858ae0c4 ./live.txt
mv ./d919fe9602ad13f7 ./18.txt
rm -rf ./ubvip1689


touch ubvip1689
grep -i "ubvip1688" ./live.txt > ./ubvip1689




foreach chk ("`cat ./ubvip1689`")
  echo $chk
  set name = `echo $chk | cut -d "," -f 1` 
  echo $name
  set file = `echo $chk | cut -d "," -f 2` 
  echo $file
  rm -rf ./path/*
  ln -s ./path/$name $file
end
